name: djmobilapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  share_plus: ^7.2.2
  open_file: ^3.2.1
  dio: ^5.3.2
  path_provider: ^2.0.15
  permission_handler: ^11.0.0
  provider: ^6.0.5
  url_launcher: ^6.1.0
  webview_flutter: ^4.11.0
  just_audio: ^0.9.34
  rxdart: ^0.27.7
  socket_io_client: ^2.0.3+1
  shared_preferences: ^2.2.2
  image_picker: ^0.8.7+3
  http: ^0.13.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.3
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  overlay_support: ^2.1.0
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sample1.png
    - assets/sample2.png
    - assets/sample3.png
    - assets/sample4.png
    - assets/afra.jpeg
    - assets/down.jpg
    - assets/organic.jpeg
    - assets/melodic.jpg
    - assets/indie.jpg
    - assets/beatport_logo.png
    - assets/your_logo.png
    - assets/default_profile.png
    - assets/default_music.jpg
    - assets/music1.png
    - assets/music2.png
    - assets/music3.png
    - assets/music4.png
